"""Render the hypothesis-engine section of the public site.

Writes a markdown page that build_site.py turns into engine.html. Every
number on the page is read from audit.db at render time, never typed in
— the same rule the inventory renderer now follows, and the reason the
site can claim its figures are recomputable.

    python build_page.py
"""
from __future__ import annotations

import json
import sqlite3
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
HUB = HERE.parent
sys.path.insert(0, str(HUB))
from pack import PACK  # noqa: E402

AUDIT = PACK.audit_db

OUT = PACK.outputs_dir / "hypothesis_engine.md"

LEVELS = PACK.causal_level_labels
NUMBER_WORDS = ["no", "one", "two", "three", "four", "five", "six", "seven",
                "eight", "nine", "ten", "eleven", "twelve"]


def n_words(n: int) -> str:
    return NUMBER_WORDS[n] if n < len(NUMBER_WORDS) else str(n)


def main() -> None:
    conn = sqlite3.connect(f"file:{AUDIT}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()

    n_cand = c.execute("SELECT COUNT(*) FROM candidates").fetchone()[0]
    n_cert = c.execute(
        "SELECT COUNT(*) FROM candidates WHERE certified=1").fetchone()[0]
    n_conv = c.execute(
        "SELECT COUNT(*) FROM candidates WHERE convergent=1").fetchone()[0]
    n_restate = c.execute(
        "SELECT COUNT(*) FROM candidates WHERE is_restatement=1").fetchone()[0]
    n_novel = c.execute("SELECT COUNT(*) FROM candidates "
                        "WHERE certified=1 AND is_restatement=0").fetchone()[0]
    n_mech_fail = c.execute("SELECT COUNT(*) FROM candidates "
                            "WHERE mechanical_pass=0").fetchone()[0]
    engines = c.execute(
        "SELECT DISTINCT engine FROM members ORDER BY engine").fetchall()

    n_q = n_words(len(list(PACK.seeds_dir.glob("Q*.json"))))
    L = ["# The hypothesis engine\n",
         "Open AI hypothesis-generation engines, run over this field's own "
         f"literature, answering the {n_q} questions the field says it "
         "cannot answer — and then tested, claim by claim, against the "
         "corpus they cite.\n",
         f"**The pipeline.** Each of the {n_q} open questions becomes a "
         "structured seed: the question in the field's own words, the "
         "verbatim evidence sentences behind it, the registry claims "
         "already at stake, and fixed corpus entry points. Every engine "
         "receives the identical prompt and reads the literature only "
         "through one read-only corpus interface, with no web access, so "
         "what differs between engines is architecture and model family "
         "rather than prompt or retrieval luck. Their output lands in one "
         "schema (the Hypothesis Output Format), is clustered across "
         "engines with provenance kept, and is then audited in the "
         "certify-or-decline discipline of "
         "[theoria](https://github.com/zaladbar/theoria): the reasoning is "
         "decomposed into steps, every citation step must resolve to a "
         "work that exists in this corpus and actually says what the step "
         "claims, and one failed load-bearing step declines the whole "
         "hypothesis.\n",
         "**Nothing here is a result about biology.** These are proposals "
         "for experiments, generated by machines and filtered for "
         "groundedness. A certified hypothesis is one whose reasoning "
         "survived audit, not one that is true.\n",
         "## This run\n",
         f"| | |\n|---|---|\n"
         f"| Candidates after cross-engine merge | {n_cand} |\n"
         f"| Reached independently by more than one engine | {n_conv} |\n"
         f"| Declined before judging (mechanical checks) | {n_mech_fail} |\n"
         f"| Certified | {n_cert} |\n"
         f"| Restatements of existing registry claims | {n_restate} |\n"
         f"| **Certified and not a restatement** | **{n_novel}** |\n"]

    if engines:
        L.append("\n## Engines\n")
        L.append("**Read this table with the bias measurement beside it.** "
                 "Each judge family passed its own family's hypotheses at a "
                 "higher rate than the other family's (Claude judges +12 "
                 "points, the Codex judge +40). Certification here required "
                 "unanimity across three Claude judges and one Codex judge, "
                 "so the Codex judge's 5% pass rate on Claude-engine output "
                 "drives most of the difference below. These counts measure "
                 "judge composition at least as much as engine quality and "
                 "are not a ranking.\n")
        L.append("| Engine | Candidates | Certified | Restatements | "
                 "Novelty yield |\n|---|---|---|---|---|")
        for e in engines:
            r = c.execute("""
              SELECT COUNT(DISTINCT c.candidate_id), SUM(c.certified),
                     SUM(c.is_restatement),
                     SUM(CASE WHEN c.certified=1 AND c.is_restatement=0
                              THEN 1 ELSE 0 END)
              FROM candidates c JOIN members m USING(candidate_id)
              WHERE m.engine=?""", (e["engine"],)).fetchone()
            L.append(f"| {e['engine']} | {r[0]} | {r[1] or 0} | "
                     f"{r[2] or 0} | {r[3] or 0} |")
        L.append("\nNovelty yield is the metric that matters: certified, "
                 "grounded, and not already on the register.\n")

    L.append("\n## Certified hypotheses\n")
    rows = c.execute(
        "SELECT * FROM candidates WHERE certified=1 AND is_restatement=0 "
        "ORDER BY seed_id, candidate_id").fetchall()
    if not rows:
        L.append("_No candidate survived certification in this run._\n")
    for r in rows:
        lvl = LEVELS.get(r["causal_level"], r["causal_level"] or "")
        L.append(f"### {r['candidate_id']} · {r['seed_id']} · "
                 f"{r['causal_level']} {lvl}\n")
        L.append(f"{r['statement']}\n")
        conv = (" Reached independently by "
                f"{r['engines']}." if r["convergent"] else "")
        L.append(f"*Proposed by {r['engines']}; {r['n_citations']} corpus "
                 f"citations; nearest existing claim {r['nearest_claim']} "
                 f"(similarity {r['nearest_similarity']}).{conv}*\n")
        if r["judge_reason"]:
            L.append(f"Audit: {r['judge_reason']}\n")

    L.append("\n## Declined\n")
    L.append("Declines are the point of the exercise and are published "
             "with their reasons.\n")
    dec = c.execute(
        "SELECT candidate_id, seed_id, statement, mechanical_fails, "
        "judge_reason FROM candidates WHERE certified=0 "
        "ORDER BY seed_id LIMIT 40").fetchall()
    L.append("| Candidate | Seed | Why it was declined |\n|---|---|---|")
    for r in dec:
        why = (r["mechanical_fails"] or r["judge_reason"]
               or "not yet judged")[:200].replace("|", "/")
        L.append(f"| {r['candidate_id']} | {r['seed_id']} | {why} |")

    L.append("\n## Reproducing these numbers\n")
    L.append("Every figure above is read from `state/audit.db` at "
             "render time. To recompute:\n")
    L.append("```sql\n-- certified, not a restatement, by engine\n"
             "SELECT m.engine, COUNT(DISTINCT c.candidate_id) AS novelty\n"
             "FROM candidates c JOIN members m USING(candidate_id)\n"
             "WHERE c.certified=1 AND c.is_restatement=0\n"
             "GROUP BY m.engine;\n```\n")
    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"  -> {OUT}")


if __name__ == "__main__":
    main()
